### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/tmpmgy02awm/tmpnede1i17.py'

### ISSUE THREAD

**Issue by Geleven7** [XueZ-phd/TFDet#2]
Thank you for your excellent work, when I run the test code for llvip 
"python tools/test.py configs/faster_rcnn/faster_rcnn_vgg16_fpn_sanitized-kaist_v5.py runs/FasterRCNN_vgg16_channelRelation_dscSEFusion_similarityMax_1/epoch_3.pth --work-dir runs/FasterRCNN_vgg16_channelRelation_dscSEFusion_similarityMax_1 --gpu-id 7 --eval bbox --out runs/FasterRCNN_vgg16_channelRelation_dscSEFusion_similarityMax_1/epoch_3.pkl" ,

An error is reported: [Errno 2] No such file or directory: '/tmp/tmpmgy02awm/tmpnede1i17.py'.

I tried to run the training code "python tools/train.py configs/faster_rcnn/faster_rcnn_vgg16_fpn_sanitized-kaist_v5.py" and it reported the same error, but the test code for coco "python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py" runs correctly. 

Is there a problem with the config file "configs/faster_rcnn/faster_rcnn_r50_fpn_dcnGWConvGloballCC_llvip.py"? 
 Looking forward to your reply

**Comment by XueZ-phd** [comment]
Thank you for your attention to our work. I did not encounter any errors when running this code in the local environment, and I apologize for any inconvenience this may have caused you. I will investigate the specific reasons and provide a response.

**Comment by XueZ-phd** [comment]
Please make sure the 'data_root' and 'img_prefix' in the config file 'configs/faster_rcnn/faster_rcnn_vgg16_fpn_sanitized-kaist_v5.py' are both modified correctly.

This work is currently under review, and I will take some time later to reorganize the code to make it more readable and user-friendly.

**Comment by Geleven7** [comment]
> "img_prefix" represents the prefix of the image file path, and you need to adjust it according to your own path. For more information, please refer to the mmdetection configure documentation.

I solved it, that was the problem, thanks for your reply and excellent work! Good luck with your paper submission and your research!

**Comment by XueZ-phd** [comment]
I'm happy to solve your problem.
