### ISSUE TITLE
No training instructions found

### ISSUE THREAD

**Issue by 12lele** [XueZ-phd/TFDet#4]
Hello, I am honored to have read your paper. 
Your paper has a clear and innovative approach. 
I would like to combine your code for research.
 Can you provide the training code

**Comment by XueZ-phd** [comment]
Hello, thank you for your interest in our work. I am currently busy revising the manuscript, and I will provide a clear training guide when I have time.

In fact, if you are familiar with the MMDetection repository, you can train the code with some modifications to the dataset path.
